---
title: "project_test"
output: html_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(knitr) 

library(lubridate)

library(dplyr)

library(scales)
```




```{r}
pgcrime17_23 <- read_csv("PGCRIME17-23.csv")

pgcrime23_26 <- read_csv("PGCRIME23-26.csv")

mococrime <- read_csv("MOCOCRIME.zip")

pgcrime <- bind_rows(pgcrime17_23, pgcrime23_26)
```



## I sorted all the crimes into seven categories (assault, burglary, auto theft, theft from auto, robbery, sex offenses and homicide) to facilitate my analysis.

```{r}
pgcrime <- pgcrime |> 
  mutate(category = case_when(
    str_detect(`Clearance Code Inc Type`, "ASSAULT") ~ "assault",
    str_detect(`Clearance Code Inc Type`, "ASSAULT, WEAPON") ~ "assault",
    str_detect(`Clearance Code Inc Type`, "ASSAULT, SHOOTING") ~ "assault",
    str_detect(`Clearance Code Inc Type`, "B & E, RESIDENTIAL") ~ "burglary",
    str_detect(`Clearance Code Inc Type`, "B & E, RESIDENTIAL (VACANT)") ~ "burglary",
    str_detect(`Clearance Code Inc Type`, "B & E, COMMERCIAL") ~ "burglary",
    str_detect(`Clearance Code Inc Type`, "B & E, OTHER") ~ "burglary",
    str_detect(`Clearance Code Inc Type`, "AUTO, STOLEN") ~ "auto theft",
    str_detect(`Clearance Code Inc Type`, "AUTO, STOLEN & RECOVERED") ~ "auto theft",
    str_detect(`Clearance Code Inc Type`, "ROBBERY, OTHER") ~ "robbery",
    str_detect(`Clearance Code Inc Type`, "ROBBERY, COMMERCIAL") ~ "robbery",
    str_detect(`Clearance Code Inc Type`, "ROBBERY, RESIDENTIAL") ~ "robbery",
    str_detect(`Clearance Code Inc Type`, "ROBBERY, VEHICLE") ~ "robbery",
    str_detect(`Clearance Code Inc Type`, "ROBBERY, VEHICLE") ~ "robbery",
    str_detect(`Clearance Code Inc Type`, "THEFT FROM AUTO") ~ "theft from auto",
    str_detect(`Clearance Code Inc Type`, "THEFT") ~ "theft",
    str_detect(`Clearance Code Inc Type`, "SEX OFFENSE") ~ "sex offense",
    str_detect(`Clearance Code Inc Type`, "HOMICIDE") ~ "homicide",
    .default = NA
  )
)


mococrime <- mococrime |>
  mutate(category = case_when(
    str_detect(`Crime Name3`, "ASSAULT - 2ND DEGREE") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - INTIMIDATION (INCLUDES STALKING)") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - PUB OFF-OTHER WEAPON") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - POL OFF-OTHER WEAPON") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - FAMILY-GUN") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - SIMPLE") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - GUN") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - NON-FAMILY-OTHER WEAPON") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - FAMILY-STRONG-ARM") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - NON-FAMILY-GUN") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - NON-FAMILY-STRONG-ARM") ~ "assault",
    str_detect(`Crime Name3`, "ATTEMPTED ASSAULT AGGRAVATED POL OFF KNIFE") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - POL OFF-STRONG-ARM") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - POL OFF-GUN") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - PUB OFF-STRONG-ARM") ~ "assault",
    str_detect(`Crime Name3`, "ASSAULT - AGGRAVATED - PUB OFF-GUN") ~ "assault",
    
    .default = NA
  )
)

mococrime <- mococrime |>
  mutate(category = case_when(
    str_detect(`Crime Name3`, "SEX OFFENSE - AGAINST CHILD-FONDLING") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX ASSAULT - FONDLING") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX OFFENSE - PEEPING TOM") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX OFFENSE - INDECENT EXPOSURE") ~ "sex offense",
    str_detect(`Crime Name3`, "COMM SEX OFF - KEEPING HOUSE ILL FAME") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX OFFENSE - INCEST WITH ADULT") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX ASSAULT - SODOMY-GIRL-GUN") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX ASSAULT - SODOMY-GIRL-WEAPON") ~ "sex offense",
    str_detect(`Crime Name3`, "COMM SEX OFF - PROCURE FOR PROSTITUTE (PIMPING)") ~ "sex offense",
    str_detect(`Crime Name3`, "COMM SEX OFF - PROCURE PROSTITUTE - MINOR") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX ASSAULT - SODOMY-WOMAN-GUN") ~ "sex offense",
    str_detect(`Crime Name3`, "COMM SEX OFF - PROSTITUTION") ~ "sex offense",
    str_detect(`Crime Name3`, "HOMOSEXUAL ACT WITH BOY") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX OFFENSE - INCEST WITH MINOR") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX ASSAULT - SODOMY-MAN-WEAPON") ~ "sex offense",
    str_detect(`Crime Name3`, "COMM SEX OFF - HOMOSEXUAL PROSTITUTION") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX ASSAULT - SODOMY-WOMAN-WEAPON") ~ "sex offense",
    str_detect(`Crime Name3`, "SEX ASSAULT - SODOMY-MAN-GUN") ~ "sex offense",
    str_detect(`Crime Name3`, "COMM SEX OFF - TRANSPORT FEMALE INTERSTATE FOR IMM") ~ "sex offense",
    .default = category
  )
)

mococrime <- mococrime |>
  mutate(category = case_when(
    str_detect(`Crime Name3`, "ROBBERY - STREET-GUN") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - RESIDENTIAL-STRONG-ARM") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - STREET-STRONG-ARM") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - STREET-OTHER WEAPON") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - BUSINESS-GUN") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - FORCIBLE PURSE SNATCHING") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY (DESCRIBE OFFENSE)") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - RESIDENTIAL-GUN") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - BUSINESS-OTHER WEAPON") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - CARJACKING - ARMED") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - RESIDENTIAL-OTHER WEAPON") ~ "robbery",
    str_detect(`Crime Name3`, "ROBBERY - BANKING-TYPE INST") ~ "robbery",
    .default = category
  )
)

mococrime <- mococrime |>
  mutate(category = case_when(
    str_detect(`Crime Name3`, "BURGLARY - SAFE-VAULT") ~ "burglary",
    str_detect(`Crime Name3`, "BURGLARY - BANKING-TYPE INST") ~ "burglary",
    str_detect(`Crime Name3`, "BURGLARY (DESCRIBE OFFENSE)") ~ "burglary",
    str_detect(`Crime Name3`, "BURGLARY - NO FORCED ENTRY-NONRESIDENTIAL") ~ "burglary",
    str_detect(`Crime Name3`, "BURGLARY - FORCED ENTRY-RESIDENTIAL") ~ "burglary",
    str_detect(`Crime Name3`, "BURGLARY - FORCED ENTRY-NONRESIDENTIAL") ~ "burglary",
    str_detect(`Crime Name3`, "BURGLARY - NO FORCED ENTRY-RESIDENTIAL") ~ "burglary",
    .default = category
  )
)

mococrime <- mococrime |>
  mutate(category = case_when(
    str_detect(`Crime Name3`, "STOLEN VEHICLE (DESCRIBE OFFENSE)") ~ "auto theft",
    str_detect(`Crime Name3`, "AUTO THEFT - VEHICLE THEFT") ~ "auto theft",
    str_detect(`Crime Name3`, "AUTO THEFT - THEFT VEHICLE BY BAILEE") ~ "auto theft",
    str_detect(`Crime Name3`, "AUTO THEFT - STRIP STOLEN VEHICLE") ~ "auto theft",
    str_detect(`Crime Name3`, "AUTO THEFT - THEFT AND STRIP VEHICLE") ~ "auto theft",
    str_detect(`Crime Name3`, "AUTO THEFT - THEFT AND SALE VEHICLE") ~ "auto theft",
    str_detect(`Crime Name3`, "AUTO THEFT - THEFT AND USE VEHICLE OTHER CRIME") ~ "auto theft",
    .default = category
  )
)

mococrime <- mococrime |>
  mutate(category = case_when(
    str_detect(`Crime Name3`, "LARCENY - FROM AUTO") ~ "theft from auto",
    str_detect(`Crime Name3`, "LARCENY - AUTO PARTS") ~ "theft from auto",
    .default = category
  )
)

mococrime <- mococrime |>
  mutate(category = case_when(
    str_detect(`Crime Name3`, "HOMICIDE - WILLFUL KILL-GUN") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE (DESCRIBE OFFENSE)") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - WILLFUL KILL") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - WILLFUL KILL-FAMILY") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - JUSTIFIABLE") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - WILLFUL KILL-FAMILY-GUN") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - WILLFUL KILL-NON-FAMILY-GUN") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - WILLFUL KILL-NON-FAMILY") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - NEGLIGENT MANSLAUGHTER") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - BY NON-POLICE - JUSTIFIABLE") ~ "homicide",
    str_detect(`Crime Name3`, "HOMICIDE - JOHN OR JANE DOE - NO WARRANT") ~ "homicide",
    .default = category
  )
)

mococrime <- mococrime |>
  mutate(category = case_when(
    str_detect(`Crime Name3`, "LARCENY (DESCRIBE OFFENSE)") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - POCKET PICKING") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - FROM INTERSTATE SHIPMENT") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - THEFT OF US GOVERNMENT PROPERTY") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - FROM COIN MACHINE") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - FROM SHIPMENT") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - FROM BANKING-TYPE INST") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - FROM MALLS") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - FROM YARDS") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - PURSE SNATCHING - NO FORCE") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - POCKET PICKING") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - POSTAL") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - FROM BLDG") ~ "theft",
    str_detect(`Crime Name3`, "LARCENY - SHOPLIFTING") ~ "theft",
    .default = category
  )
)
```





```{r}
pgcrime <- pgcrime |>
  mutate(Date = mdy(Date)) |> 
  mutate(
    month = floor_date(Date, "month")
  )
```

```{r}
mococrime <- mococrime |> 
  mutate(Date = date(mdy_hm(Start_Date_Time)))|>
      mutate(month = floor_date(Date, "month"))
```




```{r}
new_pgcrime <- pgcrime |> filter(Date < '2026-04-01', Date > '2017-03-31')
```

```{r}
new_mococrime <- mococrime |> filter(Date < '2026-04-01', Date > '2017-03-31')
```



```{r}
new_mococrime <- new_mococrime %>%
  mutate(population = 1053067)

new_pgcrime <- new_pgcrime %>%
  mutate(population = 946971)
```


```{r}
pg_assault <- new_pgcrime |> 
  filter(category == "assault") |> 
  group_by(category, month, population) |> 
  summarise(pg_total = n()) |> 
  mutate(pg_assault_rate = pg_total/population * 100000)

moco_assault <- new_mococrime |> 
  filter(category == "assault") |> 
  group_by(category, month, population) |> 
  summarise(moco_total = n()) |> 
  mutate(moco_assault_rate = moco_total/population * 100000)

combined_assault <- pg_assault |> 
  inner_join(moco_assault, join_by(category, month))



pg_sexoffense <- new_pgcrime |> 
  filter(category == "sex offense") |> 
  group_by(category, month, population) |> 
  summarise(pg_total = n()) |> 
  mutate(pg_sexoffense_rate = pg_total/population * 100000)

moco_sexoffense <- new_mococrime |> 
  filter(category == "sex offense") |> 
  group_by(category, month, population) |> 
  summarise(moco_total = n()) |> 
  mutate(moco_sexoffense_rate = moco_total/population * 100000)

combined_sexoffense <- pg_sexoffense |> 
  inner_join(moco_sexoffense, join_by(category, month))



pg_robbery <- new_pgcrime |> 
  filter(category == "robbery") |> 
  group_by(category, month, population) |> 
  summarise(pg_total = n()) |> 
  mutate(pg_robbery_rate = pg_total/population * 100000)

moco_robbery <- new_mococrime |> 
  filter(category == "robbery") |> 
  group_by(category, month, population) |> 
  summarise(moco_total = n()) |> 
  mutate(moco_robbery_rate = moco_total/population * 100000)

combined_robbery <- pg_robbery |> inner_join(moco_robbery, join_by(category, month))



pg_burglary <- new_pgcrime |> 
  filter(category == "burglary") |> 
  group_by(category, month, population) |> 
  summarise(pg_total = n()) |> 
  mutate(pg_burglary_rate = pg_total/population * 100000)

moco_burglary <- new_mococrime |> 
  filter(category == "burglary") |> 
  group_by(category, month, population) |> 
  summarise(moco_total = n()) |> 
  mutate(moco_burglary_rate = moco_total/population * 100000)

combined_burglary <- pg_burglary |> 
  inner_join(moco_burglary, join_by(category, month))



pg_autotheft <- new_pgcrime |> 
  filter(category == "auto theft") |> 
  group_by(category, month, population) |> 
  summarise(pg_total = n()) |> 
  mutate(pg_autotheft_rate = pg_total/population * 100000)

moco_autotheft <- new_mococrime |> 
  filter(category == "auto theft") |> 
  group_by(category, month, population) |> 
  summarise(moco_total = n()) |> 
  mutate(moco_autotheft_rate = moco_total/population * 100000)

combined_autotheft <- pg_autotheft |> 
  inner_join(moco_autotheft, join_by(category, month))



pg_theftfromauto <- new_pgcrime |> 
  filter(category == "theft from auto") |> 
  group_by(category, month, population) |> 
  summarise(pg_total = n()) |> 
  mutate(pg_theftfromauto_rate = pg_total/population * 100000)

moco_theftfromauto <- new_mococrime |> 
  filter(category == "theft from auto") |> 
  group_by(category, month, population) |> 
  summarise(moco_total = n()) |> 
  mutate(moco_theftfromauto_rate = moco_total/population * 100000)

combined_theftfromauto <- pg_theftfromauto |> 
  inner_join(moco_theftfromauto, join_by(category, month))



pg_homicide <- new_pgcrime |> 
  filter(category == "homicide") |> 
  group_by(category, month, population) |> 
  summarise(pg_total = n()) |> 
  mutate(pg_homicide_rate = pg_total/population * 100000)

moco_homicide <- new_mococrime |> 
  filter(category == "homicide") |> 
  group_by(category, month, population) |> 
  summarise(moco_total = n()) |> 
  mutate(moco_homicide_rate = moco_total/population * 100000)

combined_homicide <- pg_homicide |> 
  inner_join(moco_homicide, join_by(category, month))



pg_theft <- new_pgcrime |> 
  filter(category == "theft") |> 
  group_by(category, month, population) |> 
  summarise(pg_total = n()) |> 
  mutate(pg_theft_rate = pg_total/population * 100000)

moco_theft <- new_mococrime |> 
  filter(category == "theft") |> 
  group_by(category, month, population) |> 
  summarise(moco_total = n()) |> 
  mutate(moco_theft_rate = moco_total/population * 100000)

combined_theft <- pg_theft |> 
  inner_join(moco_theft, join_by(category, month))
```






